apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: demo
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30120
  type: NodePort  
  
